### ISSUE TITLE
Continuing after button press

### ISSUE THREAD

**Issue by Charl0ttedeB93** [UWCCDL/ACTR_RITL#1]
I'm trying to merge all my separate models into one. The model seems to remember the instructions in the first phase, and then presses a button. However, when I try to get the new visual input (the stimuli), the code fails. Apparently there's nothing in the visual-location buffer.

**Comment by TheRealDrDre** [comment]
When new visual chunks are created, they end up in the visual buffer only if they occur exactly in the same position as the previous buffer (i.e., exactly where the model was looking at). If that's not the case, a simple strategy could be to start each new phase (encoding, execution, probe) with a production that looks for something on the screen.
